### ISSUE TITLE
i can't get this to work!

### ISSUE THREAD

**Issue by AgentChris** [zalmoxisus/remote-redux-devtools#62]
![screenshot_2017-01-04-20-56-50](https://cloud.githubusercontent.com/assets/10263405/21655008/bae69656-d2c0-11e6-83e5-0bc70119f704.png)

I've tried to change the version but is not working.

I've a windows machine:

the current version is: 
0.5.7 for remote-redux-devtools
5.2.4 socketcluster-client

**Comment by AgentChris** [comment]
I've installed this remote-redux-devtoolx@0.5.1 using this command after i've uninstalled the previous version
npm i remote-redux-devtools@0.5.1 --save-dev
but the socketcluster-client is 5.2.4


my package.json looks like:
 "dependencies": {
    "react": "~15.4.0-rc.4",
    "react-native": "0.40.0",
    "react-redux": "^5.0.1",
    "redux": "^3.6.0",
    "redux-thunk": "^2.1.0",
    "socketcluster-client": "^5.2.4"
  },
  "devDependencies": {
    "babel-jest": "18.0.0",
    "babel-preset-react-native": "1.9.1",
    "jest": "18.1.0",
    "react-test-renderer": "~15.4.0-rc.4",
    "remote-redux-devtools": "^0.5.1"
  },

**Comment by zalmoxisus** [comment]
You should use `socketcluster-client@4` to solve that issue. Why are you adding it to your `dependencies`? Do you use it internally?

**Comment by AgentChris** [comment]
no but reactnative installs socketcluster-client is 5.2.4 by default, 
i've installed socketcluster-client@4, but i have the same problem, also I have yarn installed on the project but not sure if this cause an effect

**Comment by zalmoxisus** [comment]
@AgentChris, in the dependencies of your `package.json` you have specified `"socketcluster-client": "^5.2.4"`.
The path from your screenshot is present only in `socketcluster-client@5` not in 4.

Also you could just update reactnative to `react-native@v0.41.0-rc.0`, which fixes the path issue on Windows.

**Comment by AgentChris** [comment]
ok I'will try that, but i would prefer to use the stable version for react-native 0.40.0
thanks for your help :), i really appreciate your fast response 👍

**Comment by AgentChris** [comment]
if you want to use remote-redux-devtools on windows with react-native current version you need to install the version **0.5.0**, you can do this by using the flowing command:
yarn add remote-redux-devtools@0.5.0 --dev
or if you don't have yarn:
npm install remote-redux-devtools@0.5.0 --save-dev

**Comment by RanzQ** [comment]
I'm still getting this error with `remote-redux-devtools@0.5.7` and `react-native@0.41.0`.

**Comment by zalmoxisus** [comment]
@RanzQ are you also running on Windows 10? The error is exactly as in the screenshot above (in the `socketcluster-client` path)?  Does downgrading to `remote-redux-devtools@0.5.0` helps?

**Comment by RanzQ** [comment]
@zalmoxisus Yeah, Windows 10 and exactly the same error. Removed the devtools compose and the error is gone. Version `0.5.0` works.

**Comment by zalmoxisus** [comment]
Weird, @jhen0409's  [patch](https://github.com/facebook/react-native/pull/11641) should fix the path. Also I don't get why it's `socketcluster-client\\lib\\sctransport.j\\lib\\ws-browser.js`, it should at least be sctransport.j**s**.

**Comment by RanzQ** [comment]
The part of the path `...sctransport.j\\lib...` looks weird...

**Comment by jhen0409** [comment]
Looks like it's problem of path resolve, I found it haven't use `path.sep` in [here](https://github.com/facebook/react-native/blob/master/packager/src/node-haste/DependencyGraph/ResolutionRequest.js#L319-L322).

So https://github.com/facebook/react-native/pull/11641 isn't fixed the problem fully, let's fix it again. 😂

**Comment by lednhatkhanh** [comment]
I get the exact same problem with windows 10

**Comment by zalmoxisus** [comment]
@lednhatkhanh, as noted in [the README](https://github.com/zalmoxisus/remote-redux-devtools#installation), you should use `remote-redux-devtools@0.5.0` for Windows. At least for one month till the next release of React Native.

**Comment by juslintek** [comment]
Well same happens on macOS Sierra.

**Comment by jhen0409** [comment]
RN 0.43 should fixed the problem of top. (with https://github.com/facebook/react-native/pull/12206)

**Comment by sukeshthakare** [comment]
I also get same error on Windows 10..

8:40:50 PM: (node:6424) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2865): UnableToResolveError: Unable to resolve module C:\Users\Sukeshu\Desktop\abc\SocialApp\node_modules\socketcluster-client\lib\sctransport.j\lib\ws-browser.js from C:\Users\Sukeshu\Desktop\abc\SocialApp\node_modules\socketcluster-client\lib\sctransport.js: Directory C:\Users\Sukeshu\Desktop\abc\SocialApp\node_modules\socketcluster-client\lib\sctransport.j\lib\ws-browser.js doesn't exist

**Comment by jhen0409** [comment]
@sukeshthakare I can't reproduce it again on RN ^0.43, is your RN version number correct?

**Comment by sukeshthakare** [comment]
my RN version is 0.42.3  . see all my dependencies, 

"dependencies": {
    "expo": "^15.1.0",
    "react": "~15.4.0",
    "react-native": "0.42.3",
    "lodash": "^4.13.1",
    "moment": "^2.13.0",
    "native-base": "2.1.0-rc.2",
    "react-native-animatable": "^1.1.0",
    "react-native-button": "^1.8.2",
    "react-native-easy-grid": "0.1.8",
    "react-native-gifted-chat": "^0.1.3",
    "react-native-gifted-spinner": "0.1.0",
    "react-native-lightbox": "^0.6.0",
    "react-native-list-popover": "^1.0.5",
    "react-native-modalbox": "^1.3.9",
    "react-native-router-flux": "3.37.0",
    "react-native-search-bar": "^3.0.0",
    "react-native-simple-modal": "^4.0.2",
    "react-native-slide-down-panel": "^1.0.6",
    "react-native-swiper": "^1.5.4",
    "react-native-vector-icons": "^4.0.0",
    "react-redux": "^5.0.3",
    "redux": "^3.6.0",
    "redux-persist": "^4.4.2",
    "redux-thunk": "^2.2.0",
    "remote-redux-devtools": "^0.5.7",
    "remote-redux-devtools-on-debugger": "^0.7.0"
  }

**Comment by GeekRishabh** [comment]
@sukeshthakare 
use 
"react-native-vector-icons": "4.0.0",
"remote-redux-devtools": "0.5.0",

**Comment by jhen0409** [comment]
> my RN version is 0.42.3 . see all my dependencies

The fix is landed on React Native >= 0.43 (https://github.com/zalmoxisus/remote-redux-devtools/issues/62#issuecomment-292063644), if you can't upgrade RN version for some reasons, just use `remote-redux-devtools@0.5.0` as @GeekRishabh said.

**Comment by chrisjowen** [comment]
Still an issue with rn `^0.45.1` and dev tools `^0.5.11`

**Comment by psychobolt** [comment]
Due to some other dependencies in my project, I am require RN ^0.42.0 and redux-devtools 0.5.0. Upgrading redux-devtools will give me the path resolve issue.

**Comment by chocobuckle** [comment]
Is it still recommended that Windows 10 users use v0.5.0?
