### ISSUE TITLE
remotedev.io is offline

### ISSUE THREAD

**Issue by arekkas** [zalmoxisus/remote-redux-devtools#65]
just wanted to let you know that remotedev.io is offline for ~20 hours. :)

**Comment by zalmoxisus** [comment]
Thanks for letting me know. Yes, it's down for 16 hours (since yesterday evening). The hdd went off, and I'm waiting for the guys from the dataceter to change it and install the OS. Hopefully we're not storing anything there.

We should move it to the cloud. For now it wasn't intended to be a reliable solution, just an alternative to local server.

**Comment by arekkas** [comment]
Thanks for the update! No pressure by the way, it's awesome that this is free anyways! The server could probably run quite well on heroku, the pricing is transparent and the performance is ok and basically no maintenance required.

**Comment by zalmoxisus** [comment]
Thanks for pointing out to heroku. Installation is really easy. You can use https://remotedev.herokuapp.com/local/ now. Just add host `remotedev.herokuapp.com` and port `443` and check `secure`.

However I don't see how to use my raw domain `remotedev.io`, only `www.remotedev.io` with redirect from the domain without `www`: https://devcenter.heroku.com/articles/route-53

**Comment by arekkas** [comment]
Hm not an expert on heroku here either. It *should* be possible by pointing your A records somewhere although I didn't find anything in the docs.

**Do not put the CNAME record on the root domain** (www prefix is fine). It will break other things like MX records.

**Comment by zalmoxisus** [comment]
Heroku doesn't offer a static IP for using as A records, and doesn't provide DNS services either.

However I managed to get it work by adding PointDNS app. This requires changing nameservers, so depending on users ISPs it can require up to 24 hours for the update.

Please let me know if you get https://remotedev.io working.

**Comment by arekkas** [comment]
It works, but gives an SSL error. Thank you for your effort on this

**Comment by zalmoxisus** [comment]
Well, it took me some time to get  how to use certbot on heroku. But the missing part was that for ssl, we should point to `herokudns.com` instead of `herokuapp.com`.

Should work now.

**Comment by arekkas** [comment]
Yes, awesome! Thank you so much :)

**Comment by zalmoxisus** [comment]
Thank you too for the investigation 🙂

**Comment by lfeddern** [comment]
Hi, 

Sorry I am still having problems. I was using early yesterday afternoon and everything was working fine (using with react native).

Now getting this error in the chrome plugin:
WebSocket connection to 'wss://remotedev.io/socketcluster/' failed: WebSocket is closed before the connection is established.

Is there anything I should be trying?

Thanks for your help, this is such a great tool.

**Comment by zalmoxisus** [comment]
@lfeddern, it could be dns cache on your ISP part, which could be updated up to 24 hours. I wanted to avoid changing nameservers, but unfortunately that wasn't possible with heroku.

A simple fix is to updated you hosts file (`sudo nano /etc/hosts` on macos) and add `54.197.251.207 remotedev.io`. Or to use `remotedev.herokuapp.com` as indicated in https://github.com/zalmoxisus/remote-redux-devtools/issues/65#issuecomment-280845303.

Also consider [using a local server](https://github.com/zalmoxisus/remote-redux-devtools#communicate-via-local-server) for a more reliable service.

I'll keep the issue open then, so others can find it easer.

**Comment by lfeddern** [comment]
host file updated and working. Many thanks!

**Comment by arekkas** [comment]
@zalmoxisus unfortunately it's offline again :(

![grafik](https://cloud.githubusercontent.com/assets/3372410/23227882/c4cccd20-f93a-11e6-9dd2-8e7b4622e2c1.png)

**Comment by arekkas** [comment]
It seems like it recovered :)

**Comment by zalmoxisus** [comment]
@arekkas thanks for monitoring it. Yes, I just restarted it. I'm new to heroku and still exploring the deployment. I'll try to scale it to an additional dyno.

We're using `socketcluster` under the hood which is rather performant (comparing to `socket.io`) and when a worker crashes it starts another one assuring 100% uptime. However, it seems 512MB RAM is obviously not enough, assuming that we have lots of clients with lots of big payloads sending over.

**Comment by arekkas** [comment]
Thanks for the update! By the way, there are add ons (free) available on heroku that send you an email when the service is down (e.g. http-based check) :)

**Comment by tbehrsin** [comment]
Just to let you know it's down again.

**Comment by futpib** [comment]
@poly-media yeap, seems down again.

Easiest workaround I found following links from this thread:
1) Start local server
```
docker run -it -p 8000:8000 jhen0409/remotedev-server
```
2) Use it in the code you want to debug:
```js
		composeWithDevTools({
			hostname: 'localhost', port: 8000,
		})(applyMiddleware(...middlewares)),
```
3) Use it in the redux devtools settings:
![image](https://user-images.githubusercontent.com/4330357/48137346-e511b880-e2b2-11e8-99d3-d3608074f7df.png)

**Comment by zalmoxisus** [comment]
`remotedev.io` now has a limit of 1MB for messages and it isn't abused anymore.

**Comment by rgomezp** [comment]
I'm having issues connecting to remotedev.io I think. What is the status? @zalmoxisus
